### ISSUE TITLE
Install coffeescript automatically

### ISSUE THREAD

**Issue by mtilda** [arthurbernierjr/KofuScript#1]
I see `coffeescript` is listed as a dependency. But after running `npm i -g mambascript`, I seem to be missing `coffeescript`. My terminal looks something like this:

```
$ npm i -g mambascript
  ...
  ...
  ...
  + mambascript@0.1.1
  added 133 packages from 122 contributors in 4.344s

$ mamba index.mamba
  /c/Users/.../AppData/Roaming/npm/mamba: line 12: coffee: command not found
```

I then fix the problem by installing `coffeescript` manually:

```
$ npm i -g coffeescript
  ...
  ...
  ...
  + coffeescript@2.5.1
  added 1 package from 1 contributor in 0.247s
```

After that, the mamba commands work as expected.

**Comment by arthurbernierjr** [comment]
I'll patch this update. What needs to happen is the mamba executable needs to be rewritten in either Python, Mambascript or Regular JavaScript, I wrote it in coffeescript and haven't given it a second thought. Great Catch 👍
